description: A custom agent
loop_interval_seconds: 1.0
model_name: deepseek-r1:8b
name: New Agent
system_prompt: 'You are an AI assistant. Observe the screen and help the user.


  Respond with one of these commands:

  ACTIVITY: <description of what you see>'
